name: macOS rust 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macosbuild:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: check cargo version
      run: cargo version
